//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFAIncidentSource.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection AutoWatchSuburb {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AutoWatchSuburb"]));
            }
            set {
                this["AutoWatchSuburb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection AutoWatchAddress {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AutoWatchAddress"]));
            }
            set {
                this["AutoWatchAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection AutoWatchTypes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AutoWatchTypes"]));
            }
            set {
                this["AutoWatchTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection AutoWatchStatus {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AutoWatchStatus"]));
            }
            set {
                this["AutoWatchStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection AutoWatchRegion {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AutoWatchRegion"]));
            }
            set {
                this["AutoWatchRegion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AutoWatchAppliances {
            get {
                return ((int)(this["AutoWatchAppliances"]));
            }
            set {
                this["AutoWatchAppliances"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AutoWatchSize {
            get {
                return ((string)(this["AutoWatchSize"]));
            }
            set {
                this["AutoWatchSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://osom.cfa.vic.gov.au/public/osom/IN_COMING.rss")]
        public string GathererSourceURL {
            get {
                return ((string)(this["GathererSourceURL"]));
            }
            set {
                this["GathererSourceURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ActionDiamond {
            get {
                return ((string)(this["ActionDiamond"]));
            }
            set {
                this["ActionDiamond"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ActionSquare {
            get {
                return ((string)(this["ActionSquare"]));
            }
            set {
                this["ActionSquare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ActionCircle {
            get {
                return ((string)(this["ActionCircle"]));
            }
            set {
                this["ActionCircle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StreamURL2 {
            get {
                return ((string)(this["StreamURL2"]));
            }
            set {
                this["StreamURL2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StreamURL4 {
            get {
                return ((string)(this["StreamURL4"]));
            }
            set {
                this["StreamURL4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StreamURL5 {
            get {
                return ((string)(this["StreamURL5"]));
            }
            set {
                this["StreamURL5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StreamURL6 {
            get {
                return ((string)(this["StreamURL6"]));
            }
            set {
                this["StreamURL6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StreamURL7 {
            get {
                return ((string)(this["StreamURL7"]));
            }
            set {
                this["StreamURL7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StreamURL8 {
            get {
                return ((string)(this["StreamURL8"]));
            }
            set {
                this["StreamURL8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StreamURL9 {
            get {
                return ((string)(this["StreamURL9"]));
            }
            set {
                this["StreamURL9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StreamURL10 {
            get {
                return ((string)(this["StreamURL10"]));
            }
            set {
                this["StreamURL10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StreamURL11 {
            get {
                return ((string)(this["StreamURL11"]));
            }
            set {
                this["StreamURL11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StreamURL12 {
            get {
                return ((string)(this["StreamURL12"]));
            }
            set {
                this["StreamURL12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StreamURL13 {
            get {
                return ((string)(this["StreamURL13"]));
            }
            set {
                this["StreamURL13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StreamURL14 {
            get {
                return ((string)(this["StreamURL14"]));
            }
            set {
                this["StreamURL14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StreamURL15 {
            get {
                return ((string)(this["StreamURL15"]));
            }
            set {
                this["StreamURL15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StreamURL16 {
            get {
                return ((string)(this["StreamURL16"]));
            }
            set {
                this["StreamURL16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StreamURL17 {
            get {
                return ((string)(this["StreamURL17"]));
            }
            set {
                this["StreamURL17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StreamURL18 {
            get {
                return ((string)(this["StreamURL18"]));
            }
            set {
                this["StreamURL18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StreamURL20 {
            get {
                return ((string)(this["StreamURL20"]));
            }
            set {
                this["StreamURL20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StreamURL22 {
            get {
                return ((string)(this["StreamURL22"]));
            }
            set {
                this["StreamURL22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StreamURL23 {
            get {
                return ((string)(this["StreamURL23"]));
            }
            set {
                this["StreamURL23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StreamURL24 {
            get {
                return ((string)(this["StreamURL24"]));
            }
            set {
                this["StreamURL24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ActionCircleArgs {
            get {
                return ((string)(this["ActionCircleArgs"]));
            }
            set {
                this["ActionCircleArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ActionSquareArgs {
            get {
                return ((string)(this["ActionSquareArgs"]));
            }
            set {
                this["ActionSquareArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ActionDiamondArgs {
            get {
                return ((string)(this["ActionDiamondArgs"]));
            }
            set {
                this["ActionDiamondArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%STREAM%")]
        public string StreamListenerArgs {
            get {
                return ((string)(this["StreamListenerArgs"]));
            }
            set {
                this["StreamListenerArgs"] = value;
            }
        }
    }
}
