//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTFBIncidentSource.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://esa.act.gov.au/feeds/currentincidents.xml")]
        public string IncidentSourceURL {
            get {
                return ((string)(this["IncidentSourceURL"]));
            }
            set {
                this["IncidentSourceURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StreamURL {
            get {
                return ((string)(this["StreamURL"]));
            }
            set {
                this["StreamURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ActionDiamond {
            get {
                return ((string)(this["ActionDiamond"]));
            }
            set {
                this["ActionDiamond"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ActionDiamondArgs {
            get {
                return ((string)(this["ActionDiamondArgs"]));
            }
            set {
                this["ActionDiamondArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ActionSquare {
            get {
                return ((string)(this["ActionSquare"]));
            }
            set {
                this["ActionSquare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ActionSquareArgs {
            get {
                return ((string)(this["ActionSquareArgs"]));
            }
            set {
                this["ActionSquareArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ActionCircle {
            get {
                return ((string)(this["ActionCircle"]));
            }
            set {
                this["ActionCircle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ActionCircleArgs {
            get {
                return ((string)(this["ActionCircleArgs"]));
            }
            set {
                this["ActionCircleArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection AutoWatchSuburbs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AutoWatchSuburbs"]));
            }
            set {
                this["AutoWatchSuburbs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection AutoWatchLocations {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AutoWatchLocations"]));
            }
            set {
                this["AutoWatchLocations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection AutoWatchStatuses {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AutoWatchStatuses"]));
            }
            set {
                this["AutoWatchStatuses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection AutoWatchTypes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AutoWatchTypes"]));
            }
            set {
                this["AutoWatchTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoWatchEnabled {
            get {
                return ((bool)(this["AutoWatchEnabled"]));
            }
            set {
                this["AutoWatchEnabled"] = value;
            }
        }
    }
}
